version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3001:3000"
    # If you want to run `yarn dev` at docker compose startup
    # command: sh -c "yarn dev"
  backend:
    build: ./backend
    container_name: go-api
    ports:
      - '8088:8080'
    volumes:
      - ./backend:/go/src/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dev
    tty: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    volumes:
      - ./backend/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - "3400:3306"
    tty: true
  nginx:
    image: nginx
    depends_on:
      - backend
    container_name: nginx
    ports:
        - '80:80'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
